routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('welcome');
});

Auth::routes();


Route::get('/welcome', 'Web\PageController@blog')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');


Route::get('/project/{slug}', 'Web\PageController@project')->name('project');
Route::get('/referance/{slug}', 'Web\PageController@referance')->name('referance');
Route::get('/partner/{slug}', 'Web\PageController@partner')->name('partner');
Route::get('/whatwedo/{slug}', 'Web\PageController@whatwedo')->name('whatwedo');
Route::get('/team/{slug}', 'Web\PageController@team')->name('team');
Route::get('/slider/{slug}', 'Web\PageController@slider')->name('slider');
Route::get('/post/{slug}', 'Web\PageController@post')->name('post');
Route::get('/category/{slug}', 'Web\PageController@category')->name('category');
Route::get('/tag/{slug}', 'Web\PageController@tag')->name('tag');
Route::get('/article/{slug}', 'Web\PageController@article')->name('article');


Route::resource('tags','Admin\TagController');
Route::resource('categories','Admin\CategoryController');
Route::resource('refcategories','Admin\RefCategoryController');
Route::resource('posts','Admin\PostController');
Route::resource('projects','Admin\ProjectController');
Route::resource('sliders','Admin\SliderController');
Route::resource('aboutuses','Admin\AboutusController');
Route::resource('contacts','Admin\ContactController');
Route::resource('referanslar','Admin\ReferanceController');
Route::resource('teams','Admin\TeamController');
Route::resource('calender','Admin\CalenderController');
Route::resource('articless','Admin\ArticleController');
Route::resource('whatwedoess','Admin\WhatWeDoController');
Route::resource('howdoes','Admin\HowDoController');
Route::resource('partners','Admin\PartnerController');


Route::name('web.pages.')->group(function () {
    Route::get('referances', 'Web\ReferanceController@referance')->name('referances');
    Route::get('partnerss', 'Web\PartnerController@index')->name('partnerss');
    Route::get('about-us', 'Web\AboutUsController@index')->name('about-us');
    Route::get('team', 'Web\TeamController@index')->name('team');
    Route::get('contact', 'Web\ContactController@index')->name('contact');
    Route::get('activity', 'Web\ActivityController@index')->name('activity');
    Route::get('articles', 'Web\ArticleController@index')->name('articles');
    Route::get('whatwedoes', 'Web\WhaWeDoController@index')->name('whatwedoes');
});

Route::get('twitterUserTimeLine', 'TwitterController@twitterUserTimeLine');
Route::post('tweet', ['as'=>'post.tweet','uses'=>'TwitterController@tweet']);


Route::get('events', 'EventController@index');

Route::namespace('Auth')->group(function () {
    Route::get('logout', 'LoginController@logout');
});

resources/views/admin/whatwedoess/create.blade.php
@extends('layouts.inside')

@section('content')
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
          Panel </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="{{ route('whatwedoess.index') }}" class="kt-subheader__breadcrumbs-link">
            Neler Yapıyoruz ? </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="" class="kt-subheader__breadcrumbs-link">
            Neler Yapıyoruz ? Ekle </a>
        </div>
    </div>
</div>

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="row">
        <div class="col-lg-12">
            
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                        Neler Yapıyoruz ? <small> Ekle</small> 
                        </h3>
                    </div>
                    <div class="kt-portlet__head kt-portlet__head--lg">
                        <div class="kt-portlet__head-toolbar">
                            <a href="{{ url()->previous() }}" class="btn btn-clean kt-margin-r-10">
                                <i class="la la-arrow-left"></i>
                                <span class="kt-hidden-mobile">Geri</span>
                            </a>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->
                <div class="col-md-12 justify-content-center">
                {!! Form::open(['route' => 'whatwedoess.store', 'files' => true]) !!}
                        
                        @include('admin.whatwedoess.partials.form')

                    {!! Form::close() !!}
                </div>

                <!--end::Form-->
            </div>
            
        </div>
    </div>
</div>
@endsection

resources/views/admin/whatwedoess/edit.blade.php
@extends('layouts.inside')

@section('content')
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
          Panel </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="{{ route('whatwedoess.index') }}" class="kt-subheader__breadcrumbs-link">
            Neler Yapıyoruz ? </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="" class="kt-subheader__breadcrumbs-link">
            Neler Yapıyoruz ? Güncelle </a>
        </div>
    </div>
</div>

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="row">
        <div class="col-lg-12">  
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                        Neler Yapıyoruz ? <small> Güncelle</small>
                        </h3>
                    </div>
                    <div class="kt-portlet__head kt-portlet__head--lg">
                        <div class="kt-portlet__head-toolbar">
                            <a href="{{ url()->previous() }}" class="btn btn-clean kt-margin-r-10">
                                <i class="la la-arrow-left"></i>
                                <span class="kt-hidden-mobile">Geri</span>
                            </a>
                        </div>
                    </div>
                </div>

                <!--begin::Form-->
                <div class="col-md-12 justify-content-center">
                    {!! Form::model($whatwedo, ['route' => ['whatwedoess.update', $whatwedo->id], 'method' => 'PUT', 'files' => true]) !!}
                            
                        @include('admin.whatwedoess.partials.form')

                    {!! Form::close() !!}
                </div>

                <!--end::Form-->
            </div>
            
        </div>
    </div>
</div>
@endsection

resources/views/admin/whatwedoess/index.blade.php
@extends('layouts.inside')

@section('content')
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
          Panel </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="{{ route('whatwedoess.index') }}" class="kt-subheader__breadcrumbs-link">
            Neler Yapıyoruz ? </a>
            

            <!-- <span class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--active">Active link</span> -->
        </div>
    </div>
    <div class="kt-subheader__toolbar">
        <div class="kt-subheader__wrapper">
            <a href="#" class="btn kt-subheader__btn-daterange" id="kt_dashboard_daterangepicker" data-toggle="kt-tooltip" title="Select dashboard daterange" data-placement="left">
                <span class="kt-subheader__btn-daterange-title" id="kt_dashboard_daterangepicker_title">Today</span>&nbsp;
                <span class="kt-subheader__btn-daterange-date" id="kt_dashboard_daterangepicker_date">Aug 16</span>

                <!--<i class="flaticon2-calendar-1"></i>-->
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon kt-svg-icon--sm">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <rect id="bound" x="0" y="0" width="24" height="24" />
                        <path d="M4.875,20.75 C4.63541667,20.75 4.39583333,20.6541667 4.20416667,20.4625 L2.2875,18.5458333 C1.90416667,18.1625 1.90416667,17.5875 2.2875,17.2041667 C2.67083333,16.8208333 3.29375,16.8208333 3.62916667,17.2041667 L4.875,18.45 L8.0375,15.2875 C8.42083333,14.9041667 8.99583333,14.9041667 9.37916667,15.2875 C9.7625,15.6708333 9.7625,16.2458333 9.37916667,16.6291667 L5.54583333,20.4625 C5.35416667,20.6541667 5.11458333,20.75 4.875,20.75 Z" id="check" fill="#000000" fill-rule="nonzero" opacity="0.3" />
                        <path d="M2,11.8650466 L2,6 C2,4.34314575 3.34314575,3 5,3 L19,3 C20.6568542,3 22,4.34314575 22,6 L22,15 C22,15.0032706 21.9999948,15.0065399 21.9999843,15.009808 L22.0249378,15 L22.0249378,19.5857864 C22.0249378,20.1380712 21.5772226,20.5857864 21.0249378,20.5857864 C20.7597213,20.5857864 20.5053674,20.4804296 20.317831,20.2928932 L18.0249378,18 L12.9835977,18 C12.7263047,14.0909841 9.47412135,11 5.5,11 C4.23590829,11 3.04485894,11.3127315 2,11.8650466 Z M6,7 C5.44771525,7 5,7.44771525 5,8 C5,8.55228475 5.44771525,9 6,9 L15,9 C15.5522847,9 16,8.55228475 16,8 C16,7.44771525 15.5522847,7 15,7 L6,7 Z" id="Combined-Shape" fill="#000000" />
                    </g>
                </svg> </a>
            <div class="dropdown dropdown-inline" data-toggle="kt-tooltip" title="Quick actions" data-placement="left">
                <a href="#" class="btn btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon kt-svg-icon--success kt-svg-icon--md">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <polygon id="Shape" points="0 0 24 0 24 24 0 24" />
                            <path d="M5.85714286,2 L13.7364114,2 C14.0910962,2 14.4343066,2.12568431 14.7051108,2.35473959 L19.4686994,6.3839416 C19.8056532,6.66894833 20,7.08787823 20,7.52920201 L20,20.0833333 C20,21.8738751 19.9795521,22 18.1428571,22 L5.85714286,22 C4.02044787,22 4,21.8738751 4,20.0833333 L4,3.91666667 C4,2.12612489 4.02044787,2 5.85714286,2 Z" id="Combined-Shape" fill="#000000" fill-rule="nonzero" opacity="0.3" />
                            <path d="M11,14 L9,14 C8.44771525,14 8,13.5522847 8,13 C8,12.4477153 8.44771525,12 9,12 L11,12 L11,10 C11,9.44771525 11.4477153,9 12,9 C12.5522847,9 13,9.44771525 13,10 L13,12 L15,12 C15.5522847,12 16,12.4477153 16,13 C16,13.5522847 15.5522847,14 15,14 L13,14 L13,16 C13,16.5522847 12.5522847,17 12,17 C11.4477153,17 11,16.5522847 11,16 L11,14 Z" id="Combined-Shape" fill="#000000" />
                        </g>
                    </svg>

                </a>
              
            </div>
        </div>
    </div>
</div>

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                Neler Yapıyoruz ?
                </h3>
            </div>
       
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions">
                        <a href="{{ route('whatwedoess.create') }}" class="btn btn-brand btn-elevate btn-icon-sm">
                            <i class="la la-plus"></i>
                           Yeni Ekle
                        </a>
                    </div>
                </div>
            </div> 
          
           
        </div>
        <div class="kt-portlet__body">

            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                <thead>
                    <tr>
                        <th width="10px">ID</th>
                        <th>Başlık</th>
                        <th>URL</th>
                        <th colspan="3">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($whatwedoess as $whatwedo)
                    <tr>
                        <td>{{ $whatwedo->id }}</td>
                        <td>{{ $whatwedo->title }}</td>
                        <td>{{ $whatwedo->slug }}</td>
                        <td width="10px">
                            <a href="{{ route('whatwedoess.show', $whatwedo->id) }}" class="btn btn-sm btn-default">Görüntüle</a>
                        </td>
                        <td width="10px">
                            <a href="{{ route('whatwedoess.edit', $whatwedo->id) }}" class="btn btn-sm btn-default">Düzenle</a>
                        </td>
                        <td width="10px">
                            {!! Form::open(['route' => ['whatwedoess.destroy', $whatwedo->id], 'method' => 'DELETE']) !!}
                                <button class="btn btn-sm btn-danger">
                                    Sil
                                </button>                           
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $whatwedoess->render() }}
            <!--end: Datatable -->
        </div>
    </div>
</div>




@endsection

resources/views/admin/whatwedoess/show.blade.php
@extends('layouts.inside')

@section('content')
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
            Panel </h3>
        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="{{ route('whatwedoess.index') }}" class="kt-subheader__breadcrumbs-link">
            Neler Yapıyoruz ? </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="" class="kt-subheader__breadcrumbs-link">
            Neler Yapıyoruz ? Görüntüle </a>

        </div>
    </div>
  
</div>

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="row">
        <div class="col-lg-12">

            <!--begin::Portlet-->
            <div class="kt-portlet kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">
                <div class="kt-portlet__head kt-portlet__head--lg" style="">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">Neler Yapıyoruz ? <small>Görüntüle</small></h3>
                    </div>
                    <div class="kt-portlet__head kt-portlet__head--lg">
                        <div class="kt-portlet__head-toolbar">
                            <a href="{{ url()->previous() }}" class="btn btn-clean kt-margin-r-10">
                                <i class="la la-arrow-left"></i>
                                <span class="kt-hidden-mobile">Geri</span>
                            </a>
                        </div>
                    </div>
                </div>
               
                <div class="kt-portlet__body">
                    <table class="table table-bordered">
                        <tbody><tr>
                            <td style="width: 30%"><strong>Başlık</strong></td>
                            <td>
                             {{ $whatwedo->title }}
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 30%"><strong>Açıklama</strong></td>
                            <td>
                            {{ $whatwedo->slug }}
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 30%"><strong>Resim</strong></td>
                            <td>
                            @if($material->file)
                                <img src="{{ $material->file }}" class="img-responsive">
                            @endif
                            </td>
                        </tr>
                       
                    </tbody>
                </table>
                </div>


            </div>
        </div>
    </div>
</div>
@endsection